import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Welcome to Raqeb": "Welcome to Raqeb",
          "Simplifying Finance, Accelerating Growth":
              "Simplifying Finance, Accelerating Growth",
          "Manage your finances smarter, track multiple bank accounts, and optimize your business cash flow with ease.":
              "Manage your finances smarter, track multiple bank accounts, and optimize your business cash flow with ease.",
          "Cash Flow Management": "Cash Flow Management",
          "Simplify Your Financial Insights":
              "Simplify Your Financial Insights",
          "Track your business inflows, outflows, and net cash position effortlessly. Make smarter decisions with real-time cash flow analysis.":
              "Track your business inflows, outflows, and net cash position effortlessly. Make smarter decisions with real-time cash flow analysis.",
          "Multi-Bank Account Management": "Multi-Bank Account Management",
          "All Your Finances in One Place": "All Your Finances in One Place",
          "Link all your bank accounts securely using Open Banking technology. View balances, transactions, and insights from all your accounts in one convenient platform.":
              "Link all your bank accounts securely using Open Banking technology. View balances, transactions, and insights from all your accounts in one convenient platform.",
          "Get Started": "Get Started",
          "Cash Inflow": "Cash Inflow",
          "Continue": "Continue",
          "Sign Up": "Sign Up",
          "Or": "Or",
          "Business Name": "Business Name",
          "Name": "Name",
          "Email I’D/ Mobile Number": "Email I’D/ Mobile Number",
          "Password": "Password",
          "I agree to The ": "I agree to The ",
          "Terms of Service ": "Terms of Service ",
          "Privacy \nPolicy": "Privacy \nPolicy",
          "and ": "and ",
          "I agree to the Terms of Service and Privacy Policy":
              "I agree to the Terms of Service and Privacy Policy",
          "Create Account": "Create Account",
          "Already have an account? ": "Already have an account? ",
          "Sign In": "Sign In",
          "Enter OTP": "Enter OTP",
          "Enter the OTP code sent to your registered email/phone number":
              "Enter the OTP code sent to your registered email/phone number",
          "Submit OTP": "Submit OTP",
          "Didn't receive the OTP? Resend OTP":
              "Didn't receive the OTP? Resend OTP",
          "Create PIN": "Create PIN",
          "Enter PIN": "Enter PIN",
          "Confirm PIN": "Confirm PIN",
          "Submit": "Submit",
          "Forgot PIN?": "Forgot PIN?",
          "Forgot Password?": "Forgot Password?",
          "Log In": "Log In",
          "Don't have an account? Sign Up": "Don't have an account? Sign Up",
          "Already have an account? Sign In":
              "Already have an account? Sign In",
          "Reset Password": "Reset Password",
          "Hey!": "Hey!",
          "Total Balance": "Total Balance",
          "Add New Bank": "Add New Bank",
          "Cash Flow": "Cash Flow",
          "(Last 6 Months)": "(Last 6 Months)",
          "In Flow": "In Flow",
          "Minimum": "Minimum",
          "Maximum": "Maximum",
          "Monthly Average": "Monthly Average",
          "Out Flow": "Out Flow",
          "Account Number": "Account Number",
          "Transactions": "Transactions",
          "Today": "Today",
          "This Week": "This Week",
          "This Month": "This Month",
          "This Year": "This Year",
          "Custom Range": "Custom Range",
          "Cash Outflow": "Cash Outflow",
          "Expenses": "Expenses",
          "Income": "Income",
          "Category": "Category",
          "Account": "Account",
          "Verify Account": "Verify Account",
          "Verify": "Verify",
          "General Settings": "General Settings",
          "Rate Us": "Rate Us",
          "Invite a Business": "Invite a Business",
          "Chat With Us": "Chat With Us",
          "Logout": "Logout",
          "Delete Account": "Delete Account",
          "Google": "Google",
          "Forget Password": "Forget Password",
          "Enter the OTP code we just sent \nyou on your registered Email/Phone number":
              "Enter the OTP code we just sent \nyou on your registered Email/Phone number",
          "Didn’t get OTP? ": "Didn’t get OTP? ",
          "Resend OTP": "Resend OTP",
          "OTP should arrive within ": "OTP should arrive within ",
          "Phone Number": "Phone Number",
          "Fetching Bank Accounts": "Fetching Bank Accounts",
          "Change Mpin": "Change Mpin",
          "Change Language": "Change Language",
          "Are you sure you want to logout ?":
              "Are you sure you want to logout ?",
          "Cancel": "Cancel",
          "Delete my account": "Delete my account",
          "Are you sure you want to Delete Account ?":
              "Are you sure you want to Delete Account ?",
          "DELETE": "DELETE",
          "Cash In Flow": "Cash In Flow",
          "Cash Out Flow": "Cash Out Flow",
          "Create MPIN": "Create MPIN",
          "Old MPIN": "Old MPIN",
          "Enter MPIN": "Enter MPIN",
          "Confirm MPIN": "Confirm MPIN",
          "Forgot ": "Forgot ",
          "MPIN": "MPIN",
          "Please enter your name.": "Please enter your name.",
          "Please enter your email address.":
              "Please enter your email address.",
          "Please enter your business name.":
              "Please enter your business name.",
          "Please enter valid email address.":
              "Please enter valid email address.",
          "Please enter valid phone number.":
              "Please enter valid phone number.",
          "Please enter description.": "Please enter description.",
          "Please enter address.": "Please enter address.",
          "Please enter your phone number.": "Please enter your phone number.",
          "Please enter a valid address.": "Please enter a valid address.",
          "Please enter password.": "Please enter password.",
          "Please check our End-User License Agreement.":
              "Please check our End-User License Agreement.",
          "Please enter OTP.": "Please enter OTP.",
          "The password must be at least 8 characters.":
              "The password must be at least 8 characters.",
          "Please confirm your password.": "Please confirm your password.",
          "Your new password and confirm password does not match.":
              "Your new password and confirm password does not match.",
          "Something went wrong.": "Something went wrong.",
          "Please agree to terms and conditions":
              "Please agree to terms and conditions",
          "Please enter mpin.": "Please enter mpin.",
          "Your mpin and confirm mpin does not match.":
              "Your mpin and confirm mpin does not match.",
          "Remember me": "Remember me",
          "Hey ": "Hey ",
        },
        'ar_SA': {
          "Welcome to Raqeb": "مرحبا بكم في راقب",
          "Simplifying Finance, Accelerating Growth":
              "شريكك المالي لنمو الأعمال",
          "Manage your finances smarter, track multiple bank accounts, and optimize your business cash flow with ease.":
              "قم بإدارة أموالك بذكاء، وتتبع حساباتك البنكية المتعددة، وحسّن تدفقك النقدي بكل سهولة",
          "Cash Flow Management": "إدارة التدفقات النقدية",
          "Simplify Your Financial Insights": "إجعل رؤيتك المالية أبسط",
          "Track your business inflows, outflows, and net cash position effortlessly. Make smarter decisions with real-time cash flow analysis.":
              "تتبع الإيرادات والمصروفات وصافي النقد المتاح لأعمالك بسهولة. اتخذ قرارات أذكى مع تحليل التدفق النقدي اللحظي",
          "Multi-Bank Account Management": "إدارة الحسابات البنكية المتعددة",
          "All Your Finances in One Place": "جميع أموالك في مكان واحد",
          "Link all your bank accounts securely using Open Banking technology. View balances, transactions, and insights from all your accounts in one convenient platform.":
              "اربط جميع حساباتك البنكية بأمان باستخدام تقنية المصرفية المفتوحة. اعرض الأرصدة والمعاملات والرؤى لجميع حساباتك على منصة واحدة مريحة.",
          "Get Started": "إبدأ الآن",
          "Cash Inflow": "التدفقات الواردة",
          "Continue": "متابعة",
          "Sign Up": "إنشاء حساب",
          "Or": "أو",
          "Business Name": "اسم النشاط التجاري",
          "Name": "الإسم",
          "Email I’D/ Mobile Number": "البريد الإلكتروني / رقم الجوال",
          "Password": "كلمة المرور",
          "I agree to The ": "أنا أوافق على ",
          "Terms of Service ": "شروط الخدمة ",
          "Privacy \nPolicy": "سياسة الخصوصية \n",
          "and ": " و ",
          "I agree to the Terms of Service and Privacy Policy":
              "أوافق على شروط الخدمة و سياسة الخصوصية",
          "Create Account": "إنشاء حساب",
          "Already have an account?": "هل لديك حساب؟",
          "Sign In": "تسجيل الدخول",
          "Enter OTP": "إدخال رمز التحقق OTP",
          "Enter the OTP code sent to your registered email/phone number":
              "أدخل رمز التحقق المرسل إلى بريدك الإلكتروني أو رقم جوالك المسجل.",
          "Submit OTP": "إدخال رمز التحقق OTP",
          "Didn't receive the OTP? Resend OTP":
              "لم تستلم رمز التحقق؟ إعادة إرسال رمز التحقق",
          "Create PIN": "إنشاء الرقم السري",
          "Enter PIN": "أدخل الرقم السري",
          "Confirm PIN": "تأكيد الرقم السري",
          "Submit": "تأكيد",
          "Forgot PIN?": "هل نسيت الرقم السري؟",
          "Forgot Password?": "هل نسيت كلمة المرور؟",
          "Forget Password": "نسيت كلمة المرور",
          "Log In": "تسجيل الدخول",
          "Don’t have account? ": "ليس لديك حساب؟",
          "Don't have an account? Sign Up": "لا تملك حسابًا؟ إنشاء حساب",
          "Already have an account? ": " هل لديك حساب؟ ",
          "Already have an account? Sign In":
              "هل لديك حساب بالفعل؟ تسجيل الدخول",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Hey!": "مرحباً!",
          "Total Balance": "إجمالي الرصيد",
          "Add New Bank": "إضافة بنك جديد",
          "Cash Flow": "التدفق النقدي",
          "(Last 6 Months)": "(آخر 6 أشهر)",
          "In Flow": "التدفقات الواردة",
          "Minimum": "الحد الأدنى",
          "Maximum": "الحد الأقصى",
          "Monthly Average": "المتوسط الشهري",
          "Out Flow": "التدفقات الصادرة",
          "Account Number": "رقم الحساب",
          "Transactions": "المعاملات",
          "Today": "اليوم",
          "This Week": "هذا الأسبوع",
          "This Month": "هذا الشهر",
          "This Year": "هذا العام",
          "Custom Range": "نطاق مخصص",
          "Cash Outflow": "التدفقات الصادرة",
          "Expenses": "النفقات",
          "Income": "الدخل",
          "Category": "الفئات",
          "Account": "الحساب",
          "Verify Account": "توثيق الحساب",
          "General Settings": "الإعدادات العامة",
          "Rate Us": "قيّمنا",
          "Invite a Business": "دعوة شركة",
          "Chat With Us": "تواصل معنا",
          "Logout": "تسجيل الخروج",
          "Delete Account": "حذف الحساب",
          "Google": "جوجل",
          "Enter the OTP code we just sent \nyou on your registered Email/Phone number":
              "أدخل رمز OTP الذي أرسلناه إليك للتو \nعلى بريدك الإلكتروني/رقم هاتفك المسجل",
          "Didn’t get OTP? ": "لم تحصل على كلمة مرور لمرة واحدة؟",
          "Resend OTP": "إعادة إرسال كلمة المرور لمرة واحدة",
          "OTP should arrive within ": " يجب أن يصل OTP إلى الداخل ",
          "Phone Number": "رقم التليفون",
          "Verify": "يؤكد",
          "Fetching Bank Accounts": "جلب الحسابات البنكية",
          "Change Mpin": "تغيير مبين",
          "Change Language": "تغيير اللغة",
          "Are you sure you want to logout ?":
              "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "Cancel": "يلغي",
          "Delete my account": "حذف حسابي",
          "Are you sure you want to Delete Account ?":
              "هل أنت متأكد أنك تريد حذف الحساب؟",
          "DELETE": "يمسح",
          "Cash In Flow": "النقد في التدفق",
          "Cash Out Flow": "التدفق النقدي",
          "Create MPIN": "إنشاء MPIN",
          "Old MPIN": "MPIN القديم",
          "Enter MPIN": "أدخل رقم التعريف الشخصي",
          "Confirm MPIN": "قم بتأكيد الرقم MPIN",
          "Forgot ": "نسيت",
          "MPIN": "MPIN",
          "Please enter your name.": "يرجى إدخال اسمك.",
          "Please enter your email address.":
              "يرجى إدخال عنوان بريدك الإلكتروني.",
          "Please enter your business name.": "يرجى إدخال اسم عملك.",
          "Please enter valid email address.":
              "يرجى إدخال عنوان بريد إلكتروني صالح.",
          "Please enter valid phone number.": "يرجى إدخال رقم هاتف صالح.",
          "Please enter description.": "يرجى إدخال الوصف.",
          "Please enter address.": "يرجى إدخال العنوان.",
          "Please enter your phone number.": "يرجى إدخال رقم هاتفك.",
          "Please enter a valid address.": "يرجى إدخال عنوان صالح.",
          "Please enter password.": "يرجى إدخال كلمة المرور.",
          "Please check our End-User License Agreement.":
              "يرجى التحقق من اتفاقية الترخيص للمستخدم النهائي.",
          "Please enter OTP.": "يرجى إدخال رمز التحقق.",
          "The password must be at least 8 characters.":
              "يجب أن تكون كلمة المرور على الأقل 8 أحرف.",
          "Please confirm your password.": "يرجى تأكيد كلمة المرور الخاصة بك.",
          "Your new password and confirm password does not match.":
              "كلمة المرور الجديدة وكلمة المرور المؤكدة لا تتطابق.",
          "Something went wrong.": "حدث خطأ ما.",
          "Please agree to terms and conditions":
              "يرجى الموافقة على الشروط والأحكام",
          "Please enter mpin.": "يرجى إدخال الرقم السري.",
          "Your mpin and confirm mpin does not match.":
              "الرقم السري والرقم السري المؤكد لا يتطابقان.",
          "Remember me": "تذكرنى",
          "Hey ": "اهلاً",
        },
      };
}
