name: zion_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  responsive_sizer: ^3.1.1
  shimmer: ^3.0.0
  google_sign_in: ^6.2.2
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  permission_handler: ^11.0.0
  flutter_local_notifications: ^18.0.1
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  image_picker: ^1.0.4
  connectivity_plus: ^6.1.1
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  expansion_widget: ^0.1.0
  section_view: ^2.0.5
  dropdown_button2: ^2.3.7
  file_saver: ^0.2.9
  url_launcher: ^6.1.14
  intl: ^0.19.0
  hl_image_picker: ^1.2.12
  pinput: ^5.0.0
  table_calendar: ^3.1.3
  share_plus: ^10.1.3
  auto_size_text: ^3.0.0
  local_auth: ^2.3.0
  flutter_svg: ^2.0.17
  crazy_button: ^1.0.3
  vibration: ^3.1.1
  scrollable_positioned_list: ^0.3.8
  keyboard_visibility_pro: ^0.0.1
  expandable_text: ^2.3.0
  country_picker: ^2.0.20
  flutter_xlider: ^3.4.0
  youtube_player_flutter: ^9.1.2
  # youtube_player_flutter_plus: ^9.0.0

  google_maps_flutter: ^2.12.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - resources/assets/
    - resources/assets/images/
    - resources/assets/icons/
    - resources/fonts/
    - resources/raw/
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: resources/fonts/Poppins-Regular.ttf

    - family: Poppins-Medium
      fonts:
        - asset: resources/fonts/Poppins-Medium.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: resources/fonts/Poppins-SemiBold.ttf

    - family: Poppins-Bold
      fonts:
        - asset: resources/fonts/Poppins-Bold.ttf

    - family: Poppins-ExtraBold
      fonts:
        - asset: resources/fonts/Poppins-ExtraBold.ttf

    - family: Inter_18pt-Bold
      fonts:
        - asset: resources/fonts/Inter_18pt-Bold.ttf

    - family: Inter_18pt-ExtraBold
      fonts:
        - asset: resources/fonts/Inter_18pt-ExtraBold.ttf

    - family: Inter_18pt-Medium
      fonts:
        - asset: resources/fonts/Inter_18pt-Medium.ttf

    - family: Inter_18pt-Regular
      fonts:
        - asset: resources/fonts/Inter_18pt-Regular.ttf

    - family: Inter_18pt-SemiBold
      fonts:
        - asset: resources/fonts/Inter_18pt-SemiBold.ttf

    - family: Urbanist-Bold
      fonts:
        - asset: resources/fonts/Urbanist-Bold.ttf

    - family: Urbanist-ExtraBold
      fonts:
        - asset: resources/fonts/Urbanist-ExtraBold.ttf

    - family: Urbanist-Medium
      fonts:
        - asset: resources/fonts/Urbanist-Medium.ttf

    - family: Urbanist-Regular
      fonts:
        - asset: resources/fonts/Urbanist-Regular.ttf

    - family: Urbanist-SemiBold
      fonts:
        - asset: resources/fonts/Urbanist-SemiBold.ttf
